"""migrration timer

Revision ID: e3e6ab4aede7
Revises:
Create Date: 2025-05-06 20:26:18.791745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3e6ab4aede7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timer",
        sa.Column("название", sa.String(length=200), nullable=False),
        sa.Column("время помидора", sa.Integer(), nullable=False),
        sa.Column("время перерыва", sa.Integer(), nullable=False),
        sa.Column("время долгого перерыва", sa.Integer(), nullable=False),
        sa.Column("количество помидоров", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timer")
    # ### end Alembic commands ###
